### ISSUE TITLE
New features to LCA

### ISSUE THREAD

**Issue by andremonezi** [hyunsooseol/snowRMM#12]
Hello Dr. Seol, 
Thank you for your fantastic work on this Jamovi module.
Besides BIC and AIC, it would be great if you would include new estimators to evaluate the fit of the model (**SABIC** = sample-size adjusted BIC; **AWE** = approximate weight of evidence criterion; **CAIC** = consistent Akaike information criterion; **BF** = Bayes factor; **ALCPP** = average latent class posterior probability; **VLMR-LRT** = Vuong-Lo-Mendell- Rubin adjusted likelihood ratio test.
See the attached article for some very interesting indicators that can further improve the quality of data interpretation. 
I believe these same indicators 'can also be inserted into Latent Profile Analyses.
Best regards
[LCA guide.pdf](https://github.com/hyunsooseol/snowRMM/files/9490147/LCA.guide.pdf)

**Comment by hyunsooseol** [comment]
Hi [andremonezi](https://github.com/andremonezi)

Thanks for providing useful paper in LCA.
I wonder if there is a package that provides those kinds of fit index in R programs. I'll look for it sometime.

Cheers
Seol

**Comment by andremonezi** [comment]
Hi Dr. Seol,
Any news about these features?
Best regards

**Comment by hyunsooseol** [comment]
Hi [andremonezi](https://github.com/andremonezi)

I implemented those statistics to snowRMM:: **Latent Profile Analysis.**

Cheers
Seol

**Comment by hyunsooseol** [comment]
Hi [andremonezi](https://github.com/andremonezi)

I added ABIC and CAIC index  and covariates option in LCA inside snowRMM.

Best Regards
Seol

**Comment by VeraLZ** [comment]
Dear Dr. Seol,
Thank you so much to provide this module.
I would like to ask you if it would be possible to add a elbow plot to show the gains associated with additional profiles in LPA to help us to identify when the improvement in fit reaches a plateau and additional profiles become negligible thereafter.
Thank you very much

**Comment by hyunsooseol** [comment]
Hi

I am trying to add Elbow plot in LPA.

It will be available this week. I will let you know.

Best
Seol


________________________

Hyunsoo Seol, Ph.D., Professor

Dept.of Education, Chung-Ang Univ.

c.p) 010-3294-5717, o) 820-5370

H) http://jamovi.kr<http://jamovi.kr/>

[cid:958207ac-152e-4023-bf19-8d39f31e955e]
________________________________
보낸 사람: VeraLZ ***@***.***>
보낸 날짜: 2022년 11월 28일 월요일 오후 8:30
받는 사람: hyunsooseol/snowRMM ***@***.***>
참조: 설현수 ***@***.***>; Comment ***@***.***>
제목: Re: [hyunsooseol/snowRMM] New features to LCA (Issue #12)


Dear Dr. Seol,
Thank you so much to provide this module.
I would like to ask you if it would be possible to add a elbow plot to show the gains associated with additional profiles in LPA to help us to identify when the improvement in fit reaches a plateau and additional profiles become negligible thereafter.
Thank you very much

**Comment by hyunsooseol** [comment]
Hi

It is available in LCA and LPA inside snowRMM module. Update from jamovi library now.
![image](https://user-images.githubusercontent.com/37318620/204479405-2684617a-dfb9-424d-ba76-651ede4affad.png)

Best Regards
Seol

**Comment by VeraLZ** [comment]
Dear Professor Seol,

Thank you so much to add a elbow plot and for your fantastic work on Jamovi.

Best regards
