### ISSUE TITLE
Problem with LCA in snowRMM

### ISSUE THREAD

**Issue by salmjoon** [hyunsooseol/snowRMM#14]
Hello,

I'm trying to conduct a latent class analysis (LCA) in Jamovi by using the snowRMM module.

I succeeded to calculate the class model's fit indices, LCA plots and other details normally, but when I tried to allocate the class memberships for the respondents (N=1446), the memberships got allocated only to ca. 2/3 of the respondents.

I tried the function several times with different models and even with another computer, but the problem continued occuring. What could be the reason for it and how could it be fixed?

Thank you very much for helping!

**Comment by hyunsooseol** [comment]
Hi [salmjoon](https://github.com/salmjoon)

Could you share the file that occurs error or send it to snow@cau.ac.kr to see if what happens.

Best
Seol

**Comment by salmjoon** [comment]
Hi Seol,

I can't share the original data, but I made a test file, which also indicates the problem.

So, the data contains 1446 cases and 15 variables + the case id. The variables are ordinal on the 1-5 Likert scale (value 0 is missing data). I conducted a 2-class LCA using all the 15 variables, and when it was finished, I selected "Save - Class membership". After that, I went to the data sheet, and Jamovi had allocated the class memberships to only the first 81 cases. I should need the class membership for each case. 

What could be the reason behind this?

Thank you again for helping!
[testdata.xlsx](https://github.com/hyunsooseol/snowRMM/files/10064888/testdata.xlsx)

**Comment by hyunsooseol** [comment]
Hi [salmjoon](https://github.com/salmjoon)

I am trying to solve the problem. I think the problem might be due to missing data. I will let you know when the problem is solved. Instead of that module, Could you try it with **snowLatent** module?

Cheers
Seol

**Comment by salmjoon** [comment]
Hi Seol,

thank you for trying to solve it! I already tried the analysis with the original data with **snowLatent** module, and the class memberships emerged to most of the cases. However, a few (9 out of 1446) didn't still get their memberships to the data. 

When comparing those without memberships to the ones that got the memberships, there wasn't any clear difference between them in their answers. Both groups included cases with missing values in the some of the research variables.

**Comment by hyunsooseol** [comment]
Hi [salmjoon](https://github.com/salmjoon)
It may be that the corresponding case is not converged due to missing value, so membership may not be lost.

**Comment by hyunsooseol** [comment]
Hi [salmjoon](https://github.com/salmjoon)

Could you check the attached zip file? the snowLatent module is working well.
[testdata1.zip](https://github.com/hyunsooseol/snowRMM/files/10067056/testdata1.zip)

**Comment by salmjoon** [comment]
Hi Seol,

thank you. The snowLatent works perfectly with the test data, but when I try it with my original data, the 9 cases still don't get their class memberships. I don't understand why the memberships wouldn't converge to them, as with the other 1437 cases it works even if they include missing values too . The 9 cases also include a few cases with no missing values at all, and even they don't get the class memberships. Does this make sense?

**Comment by salmjoon** [comment]
> Hi [salmjoon](https://github.com/salmjoon)
> 
> the attached testdata.omv is the original data file that you sent me before in which I treated 0 as missing value in jamovi option.

Hi Seol,

I'm sorry for being unclear. That testdata.omv was a just test file I made up, because I can't share my original data set due to data privacy restrictions. 

With that testdata.omv the snowLatent module worked perfectly now and allocated the class memberships of LCA to each case. But when I tried the same with my original data set, the class memberships were still left out of nine last cases. These nine cases don't differ from the other cases that got the memberships: both include cases with some missing values in the variables. Thus, it seems that the problem isn't the missing values as they didn't prevent the class memberships to form in the other 1437 cases.

Was I any clearer now?

**Comment by hyunsooseol** [comment]
Hi [salmjoon](https://github.com/salmjoon)

Thanks for your reply. I think the snowLatent and snowRMM module are based on the algorithm of  glca and poLCA R package. so the beyond of my ability. anyway, I wil think of that. ^^

Cheers
Seol

**Comment by salmjoon** [comment]
Hi Seol,

alright, I understand. Anyhow, thank you so much for trying to help me! I really appreciate it.

**Comment by hyunsooseol** [comment]
Hi [salmjoon](https://github.com/salmjoon)

This is what poLCA R package handles missing data below;
**`na.rm`	
Logical, for how poLCA handles cases with missing values on the manifest variables. If TRUE, those cases are removed (listwise deleted) before estimating the model. If FALSE, cases with missing values are retained. Cases with missing covariates are always removed.**

Therfore, I inserted `na.rm=FALSE` in the main function `poLCA::poLCA()`, which is working well. but when the missing covariates are entered, because of missing covariates are always removed in R, the ID and membership does not matched each other.  I will push it to jamovi library this week.

Cheers
Seol

**Comment by salmjoon** [comment]
Hi Seol,

thank you for the clarification! I'll wait for your update on the module and test the analyses  with snowRMM then again. Meanwhile, I'll try to use the snowLatent module as far as I can. 

Cheers!
salmjoon

**Comment by hyunsooseol** [comment]
Hi [salmjoon](https://github.com/salmjoon)

I already pushed it to Jonathon. It will be available today and I will let you know.

With the update module,
The membership will be retained when the covariates are not entered. However, the covariates are entered,  the missing cases will be removed with the listwise method. Therefore, the ID and membership  does not match each other. This result is already confirmed by R studio. One thing that you remember is that when the covariates with no missing, the membership is working well.

Cheers
Seol

**Comment by salmjoon** [comment]
Perfect, thank you so much, Seol! This is an enormous help for me. I really appreciate it.

**Comment by hyunsooseol** [comment]
Hi [salmjoon](https://github.com/salmjoon)

Update module to the jamovi library.

![image](https://user-images.githubusercontent.com/37318620/203500445-9248932e-3705-44cc-9b75-94cb05e09d2c.png)

**Comment by salmjoon** [comment]
Hi Seol,

thank you! Now the class memberships get allocated to every single respondent! Thank you so much for fixing the module!

Only new thing that I spotted in the LCA results with the updated module was that the value of Residual df is now "NaN". Before it calculated a numeric value.

**Comment by salmjoon** [comment]
Do the "NaN" values result from the fixes done with the missing values?

**Comment by hyunsooseol** [comment]
Hi [salmjoon](https://github.com/salmjoon)

I added `na.rm=FALSE` option inside main function to get all membership. Since cases with missing values are retained, poLCA can not calculate "Residual df", "G² p" and "χ² p" .

**Comment by salmjoon** [comment]
Hi Seol,

alright, I was thinking the same too. The module works now very well, so thank you again for your help!

All the best,
salmjoon
