### ISSUE TITLE
Error message when conducting LCA with snowRMM in jamovi2.3.18

### ISSUE THREAD

**Issue by ARsosafe** [hyunsooseol/snowRMM#15]
Dear support,
when trying to conduct a Latent Class Analysis, I get the error message "This analysis has terminated, likely due to hitting a resource limit.", as soon as I add a second variable to the analysis. 
What can I do?
I would really like to use jamovi for this research project.
Thank you!
Anna

**Comment by hyunsooseol** [comment]
Hi Anna

The error message, I think, might be due to your computer environment or jamovi itself not snowRMM module.
If you want to check it, send the saved .omv files at snow@cau.ac.kr. I will take a look at.
Best
Seol
