### ISSUE TITLE
Problem with LPA on snowRMM 

### ISSUE THREAD

**Issue by cstempel** [hyunsooseol/snowRMM#18]
I'm going to start over. File is imported from SPSS to Jamovi. N=4725. LPA is 13 variables seeking 6-9 classes. LPA runs fine on equal variances and zero covariances. On models 2,3,6 I continuously get an error message "This tidyProfile has no data attached." One of many examples is attached. I can send more.
thank you,
Carl 
[ANES2020_PartyCorr_6-19-23.zip](https://github.com/hyunsooseol/snowRMM/files/11853474/ANES2020_PartyCorr_6-19-23.zip)

**Comment by hyunsooseol** [comment]
Hi [cstempel](https://github.com/cstempel)

It seems that the error message occurred because the analysis model is not suitable for the current data.

Please click on the Instructions:: page to read more about analytic models.

Best Regards
Seol

**Comment by cstempel** [comment]
HI Seol,
Thanks for the quick reply. I've read Joshua's Introduction to tidyLPA and I didn't see anything on the meaning of error messages. By the analysis model is "not suitable for the current data" does this mean that the model algorithm produces out of bound values or otherwise won't work with this configuration of variables? I'm trying to figure out if the model is unsuitable or if there is a problem with the program. Should I interpret this error message as this model (say model 6) will not work with this configuration of variables and stick to more constrained models that work fine and have high entropy, etc. 
best, 
Carl

**Comment by hyunsooseol** [comment]
Hi Carl

The snowRMM module is currently working fine. The error message does not indicate a problem with the module, but rather that the model is not suitable for the data. If possible, try to analyze your data with an R program for validation. It will probably show the same error message.

Best 
Seol

**Comment by cstempel** [comment]
Thank you! Would transforming the data, such as standardizing or centering change the suitability of the data?
