### ISSUE TITLE
Problem with SnowRMM (TidyLPA)

### ISSUE THREAD

**Issue by mistercable** [hyunsooseol/snowRMM#19]
Dear Readers,

I wanted to conduct a latent profile analysis using snowrmm -->latent profile analysis. I included my continuous variables and wanted to set the variances on "varying" and covariances on "varying". Jamovi gives an error message "_this tidyprofil has no data attached_". However, when I set the variances on "equal" and the covariances on "equal" I get the needed fit estimates. 

Can anybody help me what to do?

**Comment by pcr22km** [comment]
Did you manage to find a solution? I'm having the same problem at the moment.

**Comment by hyunsooseol** [comment]
Hi
This is not an error, but a message from R. To find out more, you will need to run it with a sample file in jamovi and specify what is different about the data you want to analyze. It's hard to tell what the problem is with the information you've provided.

Kind Regards
Seol

**Comment by hyunsooseol** [comment]
**Mclust** R package does not allow for models with varying variances and equal covariances (model 4)
