### ISSUE TITLE
Latent Class Analysis: Probabilities of 1.00 and <0.01

### ISSUE THREAD

**Issue by raelbre** [hyunsooseol/snowRMM#20]
Hello,

I am struggling with LCA for quite a while now and hope someone out there can help me. I received probabilities that do not match the significance of the resulting contingency tables. For example, the LCA tells me that Group 1 has a probability of 1.00 to have no kids but comparing this group to the others, they do not differ significantly in the numbers of kids. Does anybody know what the problem is?

Thank you so much for your help!! 

Best, 

Raël

**Comment by hyunsooseol** [comment]
hi

I opened the file you sent me and there is so much analysis that it's hard to figure out what you are asking. Furthermore, the latent layer analysis seems to be done in the snowLatent module, not the snowRMM module. It is difficult for me to solve the problem of interpreting the analysis results that is not a program bug.

Cheers
Seol

**Comment by raelbre** [comment]
hi

Thank you so much for your prompt answer. I tried again with snowRMM with the same "problem": The probabilities imply, that classes 1 and 3 have a probability of 1.00 to have no friends, although the contingency table shows that there are no significant differences between the three groups. Same goes for the probability to have kids, which does not show significant differences between the classes although the probability for class 1 to have no kids is 1.00. I find this very confusing and it feels like something is off. 

I hope I could explain it a little better this time. Thank you so much for your time! 


![Kinder](https://github.com/hyunsooseol/snowRMM/assets/148576917/6f9f37a5-9179-4256-9952-ec393af068de)
![Kinderkontakt_neu](https://github.com/hyunsooseol/snowRMM/assets/148576917/ef4942e4-556b-4a2c-974a-abe92ca925ab)
![contingency_contactfriends](https://github.com/hyunsooseol/snowRMM/assets/148576917/1195cae3-82f3-4a13-820c-5303ff3ee508)
![contingency_friends](https://github.com/hyunsooseol/snowRMM/assets/148576917/89025669-5e6c-4077-a877-dd6a012dad73)
![Friends](https://github.com/hyunsooseol/snowRMM/assets/148576917/f0d050b1-102c-4ccd-bcea-41e2af629cf5)
