### ISSUE TITLE
MLoef Test, SnowRMM

### ISSUE THREAD

**Issue by RicRoli** [hyunsooseol/snowRMM#21]
Hi there, 
For some reason the Rasch Model function doesn't give me results for the Martin Loef Test. Everything else seems to work fine.... I have 4 Steps (since I my items involve 5 Categories, right?) and therefore I try using the Polytomous Martin Loef Test. After clicking it, the result page shows a loading circle next to the result table, but nothing happens after that. Am I missing something? I will add a picture for better understanding :) 
Any help is welcome, thanks :)

![image](https://github.com/hyunsooseol/snowRMM/assets/166627638/0cf07377-06d4-489a-bd81-111ea73f3422)

**Comment by hyunsooseol** [comment]
Hi [RicRoli](https://github.com/RicRoli)

Could you share .omv file that causes error?

Best
Seol

**Comment by hyunsooseol** [comment]
Hi Hi [RicRoli](https://github.com/RicRoli)

Martin loef test can only be applied when the model is dichotomous(Step=1).

Best
Seol

**Comment by RicRoli** [comment]
I am a bit confused as to what the "Polytomous (Step >1) Martin-Loef Test" option under "testing model using eRm R package" is for then... I am sorry to bother you with this, my university professor hasn't gotten back to me yet

kind regards,

**Comment by hyunsooseol** [comment]
Sorry for that. I didn't see the analytics option correctly.

Could you share .omv file that causes error?

Kind Regards
Seol

**Comment by hyunsooseol** [comment]
Yup



내 Galaxy에서 보냄



-------- 원본 이메일 --------
발신: RicRoli ***@***.***>
날짜: 24/4/11 오후 10:58 (GMT+09:00)
받은 사람: hyunsooseol/snowRMM ***@***.***>
참조: 설현수 ***@***.***>, Comment ***@***.***>
제목: Re: [hyunsooseol/snowRMM] MLoef Test, SnowRMM (Issue #21)


No problem, thanks for your help.
Apparently i cannot upload a .omv file into this section, how can I send it to you?
Kind regards

**Comment by RicRoli** [comment]
[results-survey-vollständig2.csv - Kopie.zip](https://github.com/hyunsooseol/snowRMM/files/14956494/results-survey-vollstandig2.csv.-.Kopie.zip)

alright thanks! Here you go, hope this helps.

**Comment by hyunsooseol** [comment]
Hi [RicRoli](https://github.com/RicRoli)

I found  a bug and fixed it. I will let you know when it's available in jamovi library soon.

Thanks for reporting bugs again.

Best Regards
Seol

**Comment by hyunsooseol** [comment]
Update the module in jamovi library now.
![image](https://github.com/hyunsooseol/snowRMM/assets/37318620/2df0a6d6-f2f2-4952-b795-ee4fa3cb2a87)

Furthermore, you should remove one item in the variable box because the following assumption is violated:

![image](https://github.com/hyunsooseol/snowRMM/assets/37318620/6ed13e05-71ad-4a02-bb46-64ae49c8d304)

Best Regards
Seol

**Comment by RicRoli** [comment]
Thank you so much for your help, I will update right away! :)
