### ISSUE TITLE
cairo_ps error

### ISSUE THREAD

**Issue by MahdiAzizi0** [hyunsooseol/snowRMM#23]
[Github.zip](https://github.com/hyunsooseol/snowRMM/files/15141534/Github.zip)

Dear Seol,
Here is the file for the error below:
subscript out of bounds
Debug
Error in all.p[cbind(x.i[, i], 1:n.unique)]: subscript out of bounds
private$.run()
private$.compute(data)
mixRasch::misxRasch(data = data, steps = step, model = type, n.c = 1)",

**Comment by hyunsooseol** [comment]
Hi

You need to convert characters to numbers first.

Kind Regards
Seol
