### ISSUE TITLE
Need previous version

### ISSUE THREAD

**Issue by ckclayt1** [hyunsooseol/snowRMM#24]
Hello, I used the Latent Profile Analysis a few months ago and I could choose which model and class to save as "person membership". However, now, the system provides a best model. How can I go back to a previous version a few months ago where I was able to specify my own instead of it choosing for me?

**Comment by hyunsooseol** [comment]
Hi

I fixed bugs and updated it. You can't go back to the previous version because this one is the most accurate.

Best
Seol
