### ISSUE TITLE
Subject: DESCRIPTION file formatting issue in Remotes field

### ISSUE THREAD

**Issue by margbug01** [hyunsooseol/snowRMM#25]
Dear hyunooseol,

I encountered an issue while trying to install the snowRMM package using devtools::install_github("hyunsooseol/snowRMM"). The installation failed due to a formatting problem in the DESCRIPTION file, specifically in the Remotes field.

The error message I received was:

"Error: Failed to install 'snowRMM' from GitHub:
  Missing commas separating Remotes: 'twolodzko/equi
         cran/mixRasch'"

Upon inspection of the DESCRIPTION file, I noticed that the Remotes field is currently formatted as:

Remotes: twolodzko/equi
         cran/mixRasch

The issue is that there's a missing comma between the two remote dependencies. The correct format should be:

Remotes: twolodzko/equi,
         cran/mixRasch

Could you please update the DESCRIPTION file to include this comma? This small change should resolve the installation issue for users trying to install the package directly from GitHub.

Thank you for your attention to this matter and for maintaining this valuable package.

Best regards,
Margma

**Comment by margbug01** [comment]
I'm a new user of your snowRMM package and find it really interesting. 

By the way, I'm having some trouble understanding how to use the lcgm() function properly. The parameters, especially the 'model' part, are a bit confusing for a beginner like me.

Would it be possible to provide a simple example with some sample data and code? This would be super helpful for newcomers to understand how to use the package.

Thanks for your great work on this package!

**Comment by hyunsooseol** [comment]
Hi 

I added comma and pushed it to the github.
you will find the available references and dataset;

![image](https://github.com/user-attachments/assets/0f45afd2-f448-4953-82db-5990f9d00b31)
![image](https://github.com/user-attachments/assets/3fbe7049-1a13-456c-abd4-d6901edf0362)

Best Regards
Seol

**Comment by margbug01** [comment]
Hi, thank you for your answer, but I have no idea where I can find this page.
 I would appreciate it if you could send me the website.

**Comment by margbug01** [comment]
Hi, thank you for your answer, but I have no idea where I can find this page.
 I would appreciate it if you could send me the website.

**Comment by hyunsooseol** [comment]
https://cjvanlissa.github.io/tidySEM/articles/LCGA.html
