### ISSUE TITLE
Posteriors for LPA

### ISSUE THREAD

**Issue by DJoubert1971** [hyunsooseol/snowRMM#27]
Hello,

Would it be possible to allow for saving posterior probability values to a dataset for LPA and clustering procedures?
It tends to be more precise than cluster/class assignment so is preferable when solutions do not have very high entropy / definition.

Thank you !

DJoubert

**Comment by hyunsooseol** [comment]
Hi

Let me take a look at whether tidyLPA R package provides posterior probability values.

Kind Regards
Seol

**Comment by DJoubert1971** [comment]
The function to do so is get_data().
It provides both class assignment and a posterior for each class.

Thanks,

David

**Comment by hyunsooseol** [comment]
Hi David

Is this what you want?
![image](https://github.com/user-attachments/assets/ef884d08-b6c0-4146-9869-39842d8113cd)

Kind Regards
Seol

**Comment by DJoubert1971** [comment]
Exactly!!! If you could add this that would be awesome...

Thanks and best wishes,

David



David Joubert, Ph.D.
Associate Professor
Department of Criminology
University of Ottawa
Faculty of Social Sciences
125 University
***@***.***
(613) 562-5800<tel:(613)%20562-5800> x1803


________________________________

**Comment by hyunsooseol** [comment]
Hi David

Thanks for your reply.
We will push it in jamovi library on Monday. I will let you know when it's available.
Thanks for using snowRMM module again.

Kind Regards
Seol

**Comment by DJoubert1971** [comment]
Thank you so much.

Do you have recommendations on what to read or consult to create modules on jamovi?
I would like to adapt the depmix and lcmm packages for latent transition and trajectory models for jamovi but have no experience doing this type of conversio . How do I learn?

Best wishes,

David

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hyunsooseol** [comment]
Hi David

To create a jamovi module, you should start with the following link.
https://dev.jamovi.org/

Kind Regards
Seol

**Comment by hyunsooseol** [comment]
Hi David
It is available in jamovi library now.
![image](https://github.com/user-attachments/assets/497bd08c-dbc3-43c3-9bac-032681bb0d3e)
Kind Regards
Seol

**Comment by DJoubert1971** [comment]
Thank you so much!


David Joubert, Ph.D.
Associate Professor
Department of Criminology
University of Ottawa
Faculty of Social Sciences
125 University
***@***.***
(613) 562-5800<tel:(613)%20562-5800> x1803


________________________________

**Comment by hyunsooseol** [comment]
Hi David

**Latent Transition analysis** was implemented in snowLatent module now. Update snowLatent module in jamovi library shown below.
![image](https://github.com/user-attachments/assets/b1bde6d2-0524-4c48-8425-810de7608f41)

Kind Regards
Seol

**Comment by DJoubert1971** [comment]
Thank you!


David Joubert, Ph.D.
Associate Professor
Department of Criminology
University of Ottawa
Faculty of Social Sciences
125 University
***@***.***
(613) 562-5800<tel:(613)%20562-5800> x1803


________________________________
