### ISSUE TITLE
Latent class analysis in jamovi

### ISSUE THREAD

**Issue by fbizarrias** [hyunsooseol/snowRMM#8]
Hi, by running a latent class analysis in Jamovi, as soon as I used the data a message of "dim(x) should have a positive length" appeared. Why is it?

Best regards,

Flávio

**Comment by hyunsooseol** [comment]
Hi [fbizarrias](https://github.com/fbizarrias)

Could you attach your .omv file as a zip file? I will take a look at.

Cheers
Seol

**Comment by fbizarrias** [comment]
Hi Seol, I just discovered the problem. My data file begins with zero (to 10). Although it functions for pOLCA package in SPSS, it does not for Jamovi.

thank you for your prompt reply.

best regards

Flávio
