### ISSUE TITLE
Error in latent class analysis

### ISSUE THREAD

**Issue by anu23700** [hyunsooseol/snowRMM#9]
Hi, by running a latent class analysis in Jamovi, as soon as I used the data a message of "dim(x) should have a positive length" appeared. Why is it so? I am facing this issue since last one week. Please help.

I am also attaching the omv file for your reference
[LCA.zip](https://github.com/hyunsooseol/snowRMM/files/9094995/LCA.zip)

**Comment by hyunsooseol** [comment]
Hi

You should read instruction #2 called "To get started" befor running analysis, in which your data must be coded cosecutive values from 1 not 0. so you should record your dataset **from 1** , not 0, to infinity before running analysis.

Cheers
Seol

**Comment by anu23700** [comment]
Hi,

I also tried with data starting with code 1. Even then, It gave the same error. Might there be any other reason?

Regards
Anurag Sharma

**Comment by hyunsooseol** [comment]
Hi anu23700

I recorded it and runs OK with WIN10.  I attached the file. Just in case, update snowRMM module in the jamovi library before running it.
[sample.zip](https://github.com/hyunsooseol/snowRMM/files/9098663/sample.zip)

Cheers
Seol

**Comment by anu23700** [comment]
Ok… Will check…
Thanks a lot for you quick response
